version: "3.7"

services:
    go_app:
        build: ./server
        ports: 
            - 3000:3000
        volumes: 
            - ./server:/go/src/server
        environment:
            MYSQL_HOST: mysql_docker
            MYSQL_USER: root
            MYSQL_PASSWORD: pseudo_pass
            MYSQL_DB: book_store
        depends_on: 
            - db
        networks: 
            - inner_host
    
    db:
        image: mysql:latest
        container_name: mysql_docker
        volumes:
            - book_store_mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: pseudo_pass
            MYSQL_DATABASE: book_store
        networks: 
            - inner_host
networks:
    inner_host:
        driver: "bridge"
volumes:
    book_store_mysql_data:            
        
        